# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Etoos Technical
baseurl:        ""

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         ETOOS Tech Lab
  email:        etoostech@etoos.com
  github:       hwlee8042

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/etooseducation/etooseducation.github.io