# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Etoos Technical Blog test
baseurl:        ""
url:            "http://hwlee8042.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Lee Hye Won
  url:          http://hwlee8042.github.io
  email:        hwlee8042@gmail.com  
  github:       hwlee8042

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/hwlee8042/hwlee8042.github.io